eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://172.17.0.2:8761/eureka
ribbon:
    eureka:
        enabled: false
server:
    port: 8097
spring:
    application:
        name: apigateway-service
    cloud:
        config:
            uri: http://172.17.0.3:8888
zuul:
    routes:
        application-service:
            url: http://172.17.0.5:8086
        maintainace-service:
            url: http://172.17.0.6:9098
