eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://172.17.0.3:8761/eureka
ribbon:
    eureka:
        enabled: true
server:
    port: 8097
spring:
    application:
        name: apigateway-service
zuul:
    routes:
        application-service:
            url: http://172.17.0.6:8086
        maintainance-service:
            url: http://172.17.0.7:9098
