eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            #172.17.0.3
ribbon:
    eureka:
        enabled: true
server:
    port: 8097
spring:
    application:
        name: apigateway-service
zuul:
    routes:
        application-service:
            url: http://localhost:8086
            #172.17.0.6
        maintainance-service:
            url: http://localhost:9098
            #172.17.0.7
