
spring:
    zipkin:
        baseUrl: http://192.168.87.193:9411


eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://172.17.0.2:8761/eureka
            
            
            
            

kafka:
    topic:
        consumer:
            configs:
                fetch:
                    bootstrapservers: 192.168.87.193:9092
                    clientId: example
                    enableautocommit: false
                    groupId: example_parctice
                    name: fetch
                    offsetreset: earliest
                    timeout:
                        request: 60000
                        session: 60000
                    topic: KAFKA_TOPIC_FETCH
                fetch1:
                    bootstrapservers: 192.168.87.193:9092
                    clientId: example
                    enableautocommit: false
                    groupId: example_parctice_second
                    name: fetch
                    offsetreset: earliest
                    timeout:
                        request: 60000
                        session: 60000
                    topic: KAFKA_TOPIC_FETCH
            enabled: true
        producer:
            configs:
                fetch:
                    acks: all
                    bootstrapservers: 192.168.87.193:9092
                    clientId: example
                    name: fetch
                    timeout:
                        session: 10000
                    topic: KAFKA_TOPIC_FETCH
            enabled: true
maintainance:
    service:
        url: http://172.17.0.6:9098/api/v1/maintainance/{name}
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
