app:
    name: api-svc
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://172.17.0.2:8761/eureka

kafka:
    topic:
        consumer:
            configs:
                fetch1:
                    bootstrapservers: 192.168.87.193:9092
                    clientId: example
                    enableautocommit: false
                    groupId: example_parctice_third
                    name: fetch
                    offsetreset: earliest
                    timeout:
                        request: 60000
                        session: 60000
                    topic: KAFKA_TOPIC_FETCH
            enabled: true
logging-filter:
    enabled: true
    name: httpLoggingFilter
    order: 1
    urlPatterns: /api/v1/*

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
server:
    context-path: /MaintainanceApplication
    display-name: Maintainance-Service
    port: 8086
spring:
    application:
        name: maintainance-service
        version: '@project.version@'
    cloud:
        config:
            uri: http://172.17.0.3:8888
            
            
            eureka:
    instance:
        preferIpAddress: true
