

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
            #172.17.0.3
kafka:
    topic:
        consumer:
            configs:
                fetch1:
                    bootstrapservers: localhost:9092
                    clientId: example
                    enableautocommit: true
                    groupId: example_parctice_third
                    name: fetch1
                    offsetreset: earliest
                    timeout:
                        request: 60000
                        session: 60000
                    topic: KAFKA_TOPIC_FETCH
management:
    endpoints:
        web:
            exposure:
                include: '*'
spring:
    application:
        name: maintainance-service
    zipkin:
        baseUrl: http://localhost:9411
        
