eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://172.17.0.2:8761/eureka
kafka:
    topic:
        consumer:
            configs:
                fetch1:
                    bootstrapservers: localhost:9092
                    clientId: example
                    enableautocommit: false
                    groupId: example_parctice_third
                    name: fetch1
                    offsetreset: earliest
                    timeout:
                        request: 60000
                        session: 60000
                    topic: KAFKA_TOPIC_FETCH
            enabled: true
server:
    port: 9098
spring:
    application:
        name: maintainance-service
